(()=>{
'use strict';
if(window.__PETMASTER_EDITOR__)return;window.__PETMASTER_EDITOR__=true;
const KEY='petmaster-visual-editor-v5',OLD='petmaster-visual-editor-v4';
const load=()=>{try{let v=localStorage.getItem(KEY),o=v?JSON.parse(v):null;if(!o){const old=localStorage.getItem(OLD);o=old?JSON.parse(old):{items:{},images:[]};o.items=o.items||{};o.images=o.images||[];o.logo=o.logo||null;localStorage.setItem(KEY,JSON.stringify(o))}return o}catch{return{items:{},images:[],logo:null}}};
let db=load(),active=false,selected=null,editing=false,dirty=false,drag=null,history=[],future=[];
const textSel='h1,h2,h3,h4,h5,h6,p,span,b,strong,small,a,button,label,li,.eyebrow,.categoryCard,.product,.featureStrip,.infoSection,.contact,.heroCopy';
const logoSel='[data-pm-logo],.logo img,.brand img,.brandLogo img,header .logo,header .brand,header img';
const blocked='#pm-editor,script,style,svg,path,input,textarea,select,option';
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db));dirty=false;status('✓ Alterações salvas e preservadas')}catch{alert('Não foi possível salvar. Reduza o tamanho da imagem.')}};
const status=t=>{const x=document.querySelector('#pm-editor [data-status]');if(x)x.textContent=t};
const path=el=>{if(el.dataset.pmId)return el.dataset.pmId;let a=[],n=el;while(n&&n.nodeType===1&&n!==document.body){let i=1,p=n.previousElementSibling;while(p){if(p.tagName===n.tagName)i++;p=p.previousElementSibling}a.unshift(n.tagName.toLowerCase()+':'+i);n=n.parentElement}return a.join('/')};
const find=p=>{let cur=document.body;for(const q of p.split('/')){const [tag,num]=q.split(':');const a=[...cur.children].filter(x=>x.tagName.toLowerCase()===tag);cur=a[+num-1];if(!cur)return null}return cur};
const ensure=()=>{const k=path(selected);return db.items[k]||(db.items[k]={})};
const checkpoint=()=>{history.push(JSON.stringify(db));if(history.length>30)history.shift();future=[]};
const sync=(el,o)=>{if(!o||!el)return;if(o.html!=null&&!el.isContentEditable)el.innerHTML=o.html;for(const k of ['color','backgroundColor','fontFamily','fontSize','fontWeight','fontStyle','textAlign','textDecoration','borderRadius','opacity','zIndex','transform','width','height'])if(o[k]!=null)el.style[k]=o[k]};
const apply=()=>{Object.entries(db.items||{}).forEach(([k,o])=>{const el=find(k)||document.querySelector('[data-pm-id="'+k+'"]');if(el)sync(el,o)});for(const im of db.images||[]){let el=document.querySelector('[data-pm-image="'+im.id+'"]');if(!el){el=document.createElement('img');el.dataset.pmImage=im.id;el.dataset.pmId=im.id;el.className='pm-image-added';document.body.appendChild(el)}el.src=im.src;sync(el,im)};applyLogo()};
const getLogo=()=>document.querySelector(logoSel);
function applyLogo(){const el=getLogo(),o=db.logo;if(!el||!o)return;if(el.tagName.toLowerCase()==='img'){el.src=o.src;el.style.objectFit='contain'}else{el.style.backgroundImage=`url(${o.src})`;el.style.backgroundSize='contain';el.style.backgroundRepeat='no-repeat';el.style.backgroundPosition='center'}if(o.width)el.style.width=o.width;if(o.height)el.style.height=o.height;if(o.transform)el.style.transform=o.transform}
function select(el){if(!el)return;document.querySelectorAll('.pm-selected,.pm-logo-selected').forEach(x=>x.classList.remove('pm-selected','pm-logo-selected'));selected=el;el.classList.add(getLogo()===el?'pm-logo-selected':'pm-selected');sync(el,db.items[path(el)]||{});status(getLogo()===el?'Logo selecionada — arraste para mover ou use "Trocar logo"':'Elemento selecionado — arraste para mover')}
function toggle(){active=!active;document.body.classList.toggle('pm-editing',active);ui.querySelector('[data-a="toggle"]').textContent=active?'Editor ativo':'Ativar editor';ui.querySelectorAll('.pm-tools').forEach(x=>x.classList.toggle('on',active));if(!active){selected?.classList.remove('pm-selected','pm-logo-selected');selected=null;editing=false}else status('Selecione texto, logo, imagem, botão ou bloco')}
function style(prop,val){if(!selected)return status('Selecione um elemento');checkpoint();const o=ensure();o[prop]=val;selected.style[prop]=val;dirty=true;status('Alteração pendente — clique em Salvar')}
function imagePick(){pickImage(data=>{checkpoint();const id='img-'+Date.now();db.images.push({id,src:data,transform:'translate(80px,180px)',width:'280px'});apply();selected=document.querySelector('[data-pm-image="'+id+'"]');select(selected);dirty=true})}
function logoPick(){pickImage(data=>{checkpoint();const old=db.logo||{};db.logo={src:data,width:old.width||'150px',height:old.height||'70px',transform:old.transform||'translate(0,0)'};applyLogo();selected=getLogo();select(selected);dirty=true;status('✓ Logo trocada — agora ajuste posição e tamanho')})}
function pickImage(cb){const i=document.createElement('input');i.type='file';i.accept='image/png,image/jpeg,image/webp,image/svg+xml';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>compress(String(r.result),cb);r.readAsDataURL(f)};i.click()}
function compress(src,cb){const im=new Image();im.onload=()=>{const max=1600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.82))};im.src=src}
const css=document.createElement('style');css.textContent=`#pm-editor{position:fixed;left:10px;right:10px;bottom:10px;z-index:2147483647;font:13px Arial;color:#13253d}#pm-editor .pm-shell{max-width:1250px;margin:auto;background:#fff;border:1px solid #d9dee7;border-radius:16px;box-shadow:0 18px 70px #0005;padding:10px}.pm-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.pm-row+.pm-row{margin-top:7px}.pm-title{font-weight:800;margin-right:auto}.pm-btn,.pm-input,.pm-select{height:34px;border:1px solid #ccd3df;border-radius:8px;background:#fff;padding:0 9px;font-weight:700;color:#13253d}.pm-btn{cursor:pointer}.pm-primary{background:#10243f;color:#fff}.pm-gold{background:#d9aa45}.pm-purple{background:#6b4eff;color:#fff}.pm-danger{background:#b42318;color:#fff}.pm-tools{display:none}.pm-tools.on{display:inline-block}.pm-color{width:42px;padding:3px}.pm-number{width:66px}.pm-status{font-size:12px;color:#637083}.pm-selected{outline:2px dashed #d9aa45!important;outline-offset:4px!important}.pm-logo-selected{outline:3px solid #6b4eff!important;outline-offset:5px!important}.pm-dragging{opacity:.75;cursor:grabbing!important}.pm-image-added{position:absolute;z-index:1000;max-width:320px;height:auto;object-fit:contain;cursor:move}.heroPets{background-size:contain!important;background-repeat:no-repeat!important;background-position:center!important}@media(max-width:700px){#pm-editor{left:4px;right:4px;bottom:4px}.pm-btn,.pm-input,.pm-select{height:32px;font-size:11px}.pm-status{width:100%}}`;document.head.appendChild(css);
const ui=document.createElement('div');ui.id='pm-editor';ui.innerHTML=`<div class="pm-shell"><div class="pm-row"><b class="pm-title">✦ EDITOR VISUAL COMPLETO</b><button class="pm-btn pm-primary" data-a="toggle">Ativar editor</button><button class="pm-btn pm-purple pm-tools" data-a="logo">✦ Trocar logo</button><button class="pm-btn pm-gold pm-tools" data-a="add">＋ Imagem</button><button class="pm-btn pm-tools" data-a="undo">↶ Desfazer</button><button class="pm-btn pm-tools" data-a="redo">↷ Refazer</button><button class="pm-btn pm-gold pm-tools" data-a="save">💾 Salvar</button><button class="pm-btn pm-tools" data-a="exit">Sair</button><span class="pm-status" data-status>Editor desligado</span></div><div class="pm-row pm-tools"><button class="pm-btn" data-a="bold">B</button><button class="pm-btn" data-a="italic">I</button><button class="pm-btn" data-a="underline">U</button><button class="pm-btn" data-a="left">Esq.</button><button class="pm-btn" data-a="center">Centro</button><button class="pm-btn" data-a="right">Dir.</button><select class="pm-select" data-a="font"><option value="">Fonte</option><option>Arial</option><option>Verdana</option><option>Georgia</option><option>Times New Roman</option><option>Trebuchet MS</option><option>Courier New</option><option>Impact</option></select><input class="pm-input pm-number" data-a="size" type="number" min="8" max="120" placeholder="px"><input class="pm-input pm-color" data-a="color" type="color"><input class="pm-input pm-color" data-a="bg" type="color"><input class="pm-input pm-number" data-a="radius" type="number" min="0" max="100" placeholder="raio"><input class="pm-input pm-number" data-a="opacity" type="number" min="0" max="100" placeholder="opac."><input class="pm-input pm-number" data-a="z" type="number" min="0" max="9999" placeholder="camada"></div><div class="pm-row pm-tools"><span class="pm-status">Duplo clique no texto para editar. Arraste elementos e logo. Suas alterações anteriores são migradas automaticamente.</span></div></div>`;document.body.appendChild(ui);
ui.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;if(a==='toggle')return toggle();if(!active)return;if(a==='save')return save();if(a==='exit')return toggle();if(a==='logo')return logoPick();if(a==='add')return imagePick();if(a==='undo'){if(!history.length)return;future.push(JSON.stringify(db));db=JSON.parse(history.pop());apply();return}if(a==='redo'){if(!future.length)return;history.push(JSON.stringify(db));db=JSON.parse(future.pop());apply();return}if(!selected)return status('Selecione um elemento primeiro');if(a==='bold')return style('fontWeight',getComputedStyle(selected).fontWeight==='700'?'400':'700');if(a==='italic')return style('fontStyle',getComputedStyle(selected).fontStyle==='italic'?'normal':'italic');if(a==='underline')return style('textDecoration',getComputedStyle(selected).textDecoration.includes('underline')?'none':'underline');if(['left','center','right'].includes(a))return style('textAlign',a)});
ui.addEventListener('input',e=>{if(!active||!selected)return;const a=e.target.closest('[data-a]')?.dataset.a;if(a==='color')style('color',e.target.value);if(a==='bg')style('backgroundColor',e.target.value);if(a==='size')style('fontSize',e.target.value+'px');if(a==='radius')style('borderRadius',e.target.value+'px');if(a==='opacity')style('opacity',String(+e.target.value/100));if(a==='z')style('zIndex',e.target.value)});ui.addEventListener('change',e=>{if(active&&selected&&e.target.dataset.a==='font')style('fontFamily',e.target.value)});
document.addEventListener('dblclick',e=>{if(!active||e.target.closest('#pm-editor'))return;const el=e.target.closest(textSel);if(!el)return;select(el);editing=true;el.contentEditable='true';el.focus();status('EDITANDO: selecione somente o trecho desejado')});
document.addEventListener('input',e=>{if(active&&editing&&e.target===selected){checkpoint();const o=ensure();o.html=selected.innerHTML;dirty=true}});
document.addEventListener('pointerdown',e=>{if(!active||e.target.closest('#pm-editor')||editing)return;let el=e.target.closest(logoSel+', [data-pm-image]');if(!el)el=e.target.closest(textSel);if(!el||el.closest('#pm-editor'))return;select(el);drag={el,x:e.clientX,y:e.clientY};el.classList.add('pm-dragging');e.preventDefault()});
document.addEventListener('pointermove',e=>{if(!drag)return;drag.el.style.transform=`translate(${e.clientX-drag.x}px,${e.clientY-drag.y}px)`});
document.addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y,el=drag.el;el.classList.remove('pm-dragging');checkpoint();if(getLogo()===el){db.logo=db.logo||{};db.logo.transform=`translate(${dx}px,${dy}px)`}else{const o=ensure();o.transform=`translate(${dx}px,${dy}px)`}dirty=true;drag=null;status('Posição alterada — clique em Salvar')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&editing){editing=false;selected?.removeAttribute('contenteditable');status('Edição de texto encerrada')}});
const banner=()=>{const b=document.querySelector('.heroPets');if(b){b.style.backgroundSize='contain';b.style.backgroundRepeat='no-repeat';b.style.backgroundPosition='center'}};new MutationObserver(()=>{if(!active){banner();apply()}}).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',()=>setTimeout(()=>{banner();apply()},300));
})();