(()=>{
'use strict';
if(window.__PETMASTER_EDITOR__)return;window.__PETMASTER_EDITOR__=true;
const KEY='petmaster-visual-editor-v4';
const textSel='h1,h2,h3,h4,h5,h6,p,span,b,strong,small,a,button,label,li,.eyebrow,.categoryCard,.product,.featureStrip,.infoSection,.contact,.heroCopy,.heroPets';
const blocked='#pm-editor,header,footer,script,style,svg,path,input,textarea,select,option';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"items":{},"images":[]}')}catch{return{items:{},images:[]}}};let db=load(),active=false,selected=null,editing=false,dirty=false,drag=null;
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db));dirty=false;status('✓ Alterações salvas neste navegador')}catch(e){alert('Não foi possível salvar. A imagem pode ser grande demais. Tente uma imagem menor.')}};
const key=el=>el.dataset.pmId||(()=>{let a=[],n=el;while(n&&n.nodeType===1&&n!==document.body&&n!==document.documentElement){let i=1,p=n.previousElementSibling;while(p){if(p.tagName===n.tagName)i++;p=p.previousElementSibling}a.unshift(n.tagName.toLowerCase()+':'+i);n=n.parentElement}return a.join('/')})();
const status=t=>{const x=document.querySelector('#pm-editor [data-status]');if(x)x.textContent=t};
const target=e=>{if(!active||e.target.closest(blocked))return null;let el=e.target.closest('[data-pm-id],h1,h2,h3,h4,h5,h6,p,span,b,strong,small,a,button,.categoryCard,.product,.featureStrip,.infoSection,.contact,.heroCopy,.heroPets');if(!el||el.closest('#pm-editor'))return null;return el};
const select=el=>{if(!el)return;document.querySelectorAll('.pm-selected').forEach(x=>x.classList.remove('pm-selected'));selected=el;el.classList.add('pm-selected');const o=db.items[key(el)]||{};sync(o);status(`${el.tagName.toLowerCase()} selecionado — arraste para mover`)};
const sync=o=>{for(const [k,v] of Object.entries(o||{})){if(k==='html')continue;selected&&selected.style.setProperty(k,v)}};
const ensure=()=>{const k=key(selected);return db.items[k]||(db.items[k]={})};
const css=document.createElement('style');css.textContent=`#pm-editor{position:fixed;left:12px;right:12px;bottom:12px;z-index:2147483647;font:13px Arial,sans-serif;color:#13253d}#pm-editor .pm-shell{max-width:1250px;margin:auto;background:#fff;border:1px solid #d9dee7;border-radius:16px;box-shadow:0 18px 70px #0005;padding:10px}.pm-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.pm-row+ .pm-row{margin-top:7px}.pm-title{font-weight:800;margin-right:auto}.pm-btn,.pm-input,.pm-select{height:34px;border:1px solid #ccd3df;border-radius:8px;background:#fff;padding:0 9px;font-weight:700;color:#13253d}.pm-btn{cursor:pointer}.pm-primary{background:#10243f;color:#fff;border-color:#10243f}.pm-gold{background:#d9aa45;color:#10243d}.pm-danger{background:#b42318;color:#fff}.pm-tools{display:none}.pm-tools.on{display:block}.pm-color{width:42px;padding:3px}.pm-number{width:66px}.pm-status{font-size:12px;color:#637083;margin-left:5px}.pm-selected{outline:2px dashed #d9aa45!important;outline-offset:4px!important}.pm-dragging{cursor:grabbing!important;opacity:.8!important}.pm-hint{font-size:11px;color:#667085}.pm-image-added{position:absolute;z-index:1000;max-width:320px;height:auto;object-fit:contain;cursor:move}.heroPets{background-size:contain!important;background-repeat:no-repeat!important;background-position:center!important}@media(max-width:700px){#pm-editor{left:5px;right:5px;bottom:5px}.pm-row{gap:4px}.pm-btn,.pm-input,.pm-select{height:32px;font-size:11px}.pm-status{width:100%}}`;document.head.appendChild(css);
const ui=document.createElement('div');ui.id='pm-editor';ui.innerHTML=`<div class="pm-shell"><div class="pm-row"><b class="pm-title">✦ EDITOR VISUAL COMPLETO</b><button class="pm-btn pm-primary" data-a="toggle">Ativar editor</button><button class="pm-btn pm-gold pm-tools" data-a="add">＋ Imagem</button><button class="pm-btn pm-tools" data-a="undo">↶ Desfazer</button><button class="pm-btn pm-tools" data-a="redo">↷ Refazer</button><button class="pm-btn pm-gold pm-tools" data-a="save">💾 Salvar</button><button class="pm-btn pm-tools" data-a="exit">Sair</button><span class="pm-status" data-status>Editor desligado</span></div><div class="pm-row pm-tools" data-toolbar><button class="pm-btn" data-a="bold"><b>B</b></button><button class="pm-btn" data-a="italic"><i>I</i></button><button class="pm-btn" data-a="underline"><u>U</u></button><button class="pm-btn" data-a="left">Esq.</button><button class="pm-btn" data-a="center">Centro</button><button class="pm-btn" data-a="right">Dir.</button><select class="pm-select" data-a="font"><option value="">Fonte</option><option>Arial</option><option>Verdana</option><option>Georgia</option><option>Times New Roman</option><option>Trebuchet MS</option><option>Courier New</option><option>Impact</option></select><input class="pm-input pm-number" data-a="size" type="number" min="8" max="120" placeholder="Fonte px"><input class="pm-input pm-color" data-a="color" type="color" title="Cor do texto"><input class="pm-input pm-color" data-a="bg" type="color" title="Cor do fundo"><input class="pm-input pm-number" data-a="radius" type="number" min="0" max="100" placeholder="Raio"><input class="pm-input pm-number" data-a="opacity" type="number" min="0" max="100" placeholder="Opac."><input class="pm-input pm-number" data-a="z" type="number" min="0" max="9999" placeholder="Camada"><button class="pm-btn" data-a="reset">Restaurar elemento</button><button class="pm-btn pm-danger" data-a="delete">Excluir imagem</button></div><div class="pm-hint pm-tools" data-hint>Duplo clique em um texto para editar somente o trecho selecionado. Arraste qualquer elemento para mudar de lugar.</div></div>`;document.body.appendChild(ui);
const tools=[...ui.querySelectorAll('.pm-tools')];const show=v=>tools.forEach(x=>x.classList.toggle('on',v));
function toggle(){active=!active;document.body.classList.toggle('pm-editing',active);ui.querySelector('[data-a="toggle"]').textContent=active?'Editor ativo':'Ativar editor';show(active);if(!active){selected?.classList.remove('pm-selected');selected=null;editing=false}else status('Clique em qualquer texto, imagem, botão ou bloco para selecionar')}
function snapshot(){return JSON.stringify(db)}let history=[],future=[];function checkpoint(){history.push(snapshot());if(history.length>30)history.shift();future=[]}function restore(s){db=JSON.parse(s);applyAll();save()}
function applyAll(){document.querySelectorAll('[data-pm-id]').forEach(el=>{const o=db.items[key(el)];if(o)syncTo(el,o)});Object.entries(db.items||{}).forEach(([k,o])=>{const el=find(k);if(el)syncTo(el,o)});for(const im of db.images||[]){if(!document.querySelector('[data-pm-image="'+im.id+'"]')){const img=document.createElement('img');img.src=im.src;img.dataset.pmImage=im.id;img.dataset.pmId=im.id;img.className='pm-image-added';document.body.appendChild(img);syncTo(img,im)}}}
function find(p){let cur=document.body;for(const q of p.split('/')){const [tag,num]=q.split(':');const a=[...cur.children].filter(x=>x.tagName.toLowerCase()===tag);cur=a[+num-1];if(!cur)return null}return cur}
function syncTo(el,o){if(o.html!=null&&!el.isContentEditable)el.innerHTML=o.html;for(const k of ['color','backgroundColor','fontFamily','fontSize','fontWeight','fontStyle','textAlign','borderRadius','opacity','zIndex','transform','width','height'])if(o[k]!=null)el.style[k]=o[k]}
function style(prop,val){if(!selected)return;checkpoint();const o=ensure();o[prop]=val;selected.style[prop]=val;dirty=true;status('Alteração pendente — Salve quando terminar')}
ui.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;if(a==='toggle')return toggle();if(!active)return;if(a==='save')return save();if(a==='exit'){if(dirty&&!confirm('Sair sem salvar?'))return;return toggle()}if(a==='undo'){if(!history.length)return;future.push(snapshot());restore(history.pop());return}if(a==='redo'){if(!future.length)return;history.push(snapshot());restore(future.pop());return}if(a==='add'){return imagePick()}if(!selected)return status('Selecione um elemento primeiro');if(a==='bold')return style('fontWeight',getComputedStyle(selected).fontWeight==='700'?'400':'700');if(a==='italic')return style('fontStyle',getComputedStyle(selected).fontStyle==='italic'?'normal':'italic');if(a==='underline')return style('textDecoration',getComputedStyle(selected).textDecoration.includes('underline')?'none':'underline');if(a==='left'||a==='center'||a==='right')return style('textAlign',a);if(a==='reset'){checkpoint();delete db.items[key(selected)];selected.removeAttribute('data-pm-id');selected.removeAttribute('style');dirty=true;return applyAll()}if(a==='delete'){if(selected.dataset.pmImage){checkpoint();db.images=db.images.filter(x=>x.id!==selected.dataset.pmImage);selected.remove();dirty=true;return}status('Por segurança, elementos originais do site não podem ser excluídos.')} });
ui.addEventListener('input',e=>{if(!selected||!active)return;const a=e.target.closest('[data-a]')?.dataset.a;if(a==='color')style('color',e.target.value);if(a==='bg')style('backgroundColor',e.target.value);if(a==='size')style('fontSize',e.target.value+'px');if(a==='radius')style('borderRadius',e.target.value+'px');if(a==='opacity')style('opacity',String(+e.target.value/100));if(a==='z')style('zIndex',e.target.value)});ui.addEventListener('change',e=>{if(!selected)return;const a=e.target.closest('[data-a]')?.dataset.a;if(a==='font')style('fontFamily',e.target.value)});
document.addEventListener('dblclick',e=>{if(!active||e.target.closest('#pm-editor'))return;const el=target(e);if(!el)return;select(el);editing=true;el.contentEditable='true';el.focus();status('EDITANDO: selecione apenas a parte do texto que quer mudar');});
document.addEventListener('input',e=>{if(!active||!editing||e.target!==selected)return;checkpoint();const o=ensure();o.html=selected.innerHTML;dirty=true;status('Texto alterado — você pode selecionar somente um trecho')});
document.addEventListener('pointerdown',e=>{if(!active||e.target.closest('#pm-editor')||editing)return;const el=target(e);if(!el)return;select(el);const r=el.getBoundingClientRect();drag={el,x:e.clientX,y:e.clientY,base:getComputedStyle(el).transform==='none'?'':getComputedStyle(el).transform};el.classList.add('pm-dragging');e.preventDefault();});
document.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.el.style.transform=`translate(${dx}px,${dy}px)`;});
document.addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;const el=drag.el;el.classList.remove('pm-dragging');checkpoint();const o=ensure();o.transform=`translate(${dx}px,${dy}px)`;dirty=true;drag=null;status('Posição alterada — clique em Salvar')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&editing){editing=false;selected?.removeAttribute('contenteditable');status('Edição de texto encerrada')}});
function imagePick(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>compress(String(r.result),data=>{checkpoint();const id='img-'+Date.now();db.images.push({id,src:data,transform:'translate(80px,180px)',width:'280px'});applyAll();selected=document.querySelector('[data-pm-image="'+id+'"]');select(selected);dirty=true;status('Imagem adicionada. Arraste para qualquer lugar e Salve.')});};r.readAsDataURL(f)};input.click()}
function compress(src,cb){const im=new Image();im.onload=()=>{const max=1600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.82))};im.src=src}
const oldBanner=()=>{const b=document.querySelector('.heroPets');if(b){b.style.backgroundSize='contain';b.style.backgroundRepeat='no-repeat';b.style.backgroundPosition='center'}};
new MutationObserver(()=>{if(!active){oldBanner();applyAll()}}).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',()=>setTimeout(()=>{oldBanner();applyAll()},300));
})();