import React,{useEffect,useMemo,useState}from'react';
import{Package,ClipboardList,Users,CalendarDays,BarChart3,Boxes,RefreshCw,X,Check,Clock,Truck,Search,Plus,Save,Trash2,Image as ImageIcon}from'lucide-react';
import{supabase}from'./auth';
const money=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`;
const statusOptions=['recebido','confirmado','preparando','enviado','concluido','cancelado'];
const appointmentOptions=['agendado','confirmado','em atendimento','concluido','cancelado'];
const DEFAULT_LOGO='/logo.svg?v=4';
export default function AdminPanel({onClose}){
 const[tab,setTab]=useState('dashboard'),[orders,setOrders]=useState([]),[products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[appointments,setAppointments]=useState([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[logoDraft,setLogoDraft]=useState(DEFAULT_LOGO),[logoSaved,setLogoSaved]=useState(false);
 useEffect(()=>{try{setLogoDraft(localStorage.getItem('petmaster-logo')||DEFAULT_LOGO)}catch{}},[]);
 const load=async()=>{setLoading(true);const[o,p,c,a]=await Promise.all([supabase.from('orders').select('*').order('created_at',{ascending:false}),supabase.from('products').select('*').order('name'),supabase.from('customer_profiles').select('*').order('created_at',{ascending:false}),supabase.from('appointments').select('*').order('scheduled_at',{ascending:true})]);setOrders(o.data||[]);setProducts(p.data||[]);setCustomers(c.data||[]);setAppointments(a.data||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const updateOrder=async(id,status)=>{await supabase.from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);await load()};
 const updateAppointment=async(id,status)=>{await supabase.from('appointments').update({status}).eq('id',id);await load()};
 const saveProduct=async()=>{if(!editing)return;setSaving(true);const payload={name:editing.name,description:editing.description||'',price:Number(editing.price)||0,old_price:editing.old_price?Number(editing.old_price):null,image_url:editing.image_url||'',category:editing.category||'Alimentação',stock:Number(editing.stock)||0,active:editing.active!==false,updated_at:new Date().toISOString()};if(editing.id)await supabase.from('products').update(payload).eq('id',editing.id);else await supabase.from('products').insert(payload);setSaving(false);setEditing(null);load()};
 const deleteProduct=async id=>{if(!confirm('Excluir este produto?'))return;await supabase.from('products').update({active:false,updated_at:new Date().toISOString()}).eq('id',id);load()};
 const filteredProducts=useMemo(()=>products.filter(p=>(p.name||'').toLowerCase().includes(query.toLowerCase())),[products,query]);
 const revenue=orders.filter(o=>o.status!=='cancelado').reduce((s,o)=>s+Number(o.total||0),0),pending=orders.filter(o=>!['concluido','cancelado'].includes(o.status||'recebido')).length,lowStock=products.filter(p=>Number(p.stock)<=5&&p.active!==false).length;
 const nav=[['dashboard','Dashboard',BarChart3],['orders','Pedidos',ClipboardList],['products','Produtos',Package],['stock','Estoque',Boxes],['logo','Logo',ImageIcon],['customers','Clientes',Users],['appointments','Agendamentos',CalendarDays]];
 const chooseLogo=e=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{setLogoDraft(String(r.result));setLogoSaved(false)};r.readAsDataURL(f)};
 const saveLogo=()=>{try{localStorage.setItem('petmaster-logo',logoDraft);window.dispatchEvent(new Event('petmaster-logo-changed'));setLogoSaved(true)}catch{alert('Não foi possível salvar esta imagem. Escolha uma imagem menor.')}};
 const restoreLogo=()=>{setLogoDraft(DEFAULT_LOGO);localStorage.removeItem('petmaster-logo');window.dispatchEvent(new Event('petmaster-logo-changed'));setLogoSaved(true)};
 return <section className="admin"><div className="adminTop"><div><span className="eyebrow">PAINEL ADMINISTRATIVO</span><h2>Gestão PetMaster</h2></div><div className="adminButtons"><button className="goldBtn" onClick={load}><RefreshCw/> Atualizar</button><button className="goldBtn" onClick={onClose}><X/> Fechar</button></div></div><div className="adminNav">{nav.map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/> {label}</button>)}</div>{loading&&tab!=='logo'?<p>Carregando dados...</p>:<>
 {tab==='dashboard'&&<><div className="adminGrid">{[[BarChart3,'Pedidos',orders.length],[Package,'Produtos',products.filter(p=>p.active!==false).length],[Users,'Clientes',customers.length],[CalendarDays,'Agendamentos',appointments.length]].map(([I,l,n])=><div className="adminCard" key={l}><I/><div><b>{l}</b><span>{n} registrados</span></div></div>)}</div><div className="adminGrid"><div className="adminCard"><Check/><div><b>Vendas</b><strong>{money(revenue)}</strong></div></div><div className="adminCard"><Clock/><div><b>Pedidos em andamento</b><strong>{pending}</strong></div></div><div className="adminCard"><Boxes/><div><b>Estoque baixo</b><strong>{lowStock}</strong></div></div></div></>}
 {tab==='logo'&&<div className="logoEditorPanel"><div><span className="eyebrow">IDENTIDADE VISUAL</span><h2>Editar logo</h2><p>Escolha a logo que será exibida no site. O botão Salvar mantém a escolha neste navegador.</p><label className="logoUpload"><ImageIcon/><span>Selecionar nova logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={chooseLogo}/></span></label><div className="adminButtons"><button className="goldBtn" onClick={restoreLogo}>Restaurar logo oficial</button><button className="primary" onClick={saveLogo}><Save/> {logoSaved?'Logo salva':'Salvar logo'}</button></div></div><div className="logoEditorPreview"><span>PRÉ-VISUALIZAÇÃO</span><div><img src={logoDraft} alt="Pré-visualização da logo"/></div></div></div>}
 {tab==='orders'&&<div className="adminGrid">{orders.length?orders.map(o=><div className="adminCard" key={o.id}><ClipboardList/><div><b>Pedido {o.order_number||`#${o.id}`}</b><span>{o.customer_name||'Cliente'} · {o.customer_phone||'Sem telefone'}</span><span>{money(o.total)} · {o.payment_method||'Pagamento não informado'}</span><strong>{o.status||'recebido'}</strong></div><select value={o.status||'recebido'} onChange={e=>updateOrder(o.id,e.target.value)}>{statusOptions.map(s=><option key={s} value={s}>{s}</option>)}</select></div>):<p>Nenhum pedido registrado.</p>}</div>}
 {tab==='products'&&<><div className="adminTop"><div><h3>Produtos</h3></div><div className="adminButtons"><input placeholder="Buscar produto" value={query} onChange={e=>setQuery(e.target.value)}/><button className="goldBtn" onClick={()=>setEditing({name:'Novo produto',price:0,old_price:'',category:'Alimentação',stock:0,image_url:'',description:'',active:true})}><Plus/> Adicionar</button></div></div><div className="adminGrid">{filteredProducts.map(p=><div className="adminCard" key={p.id}><img src={p.image_url||'/logo.svg'} alt=""/><div><b>{p.name}</b><span>{p.category}</span><strong>{money(p.price)}</strong><span>Estoque: {p.stock}</span></div><button onClick={()=>setEditing({...p})}>Editar</button><button className="danger" onClick={()=>deleteProduct(p.id)}><Trash2/></button></div>)}</div></>}
 {tab==='stock'&&<div className="adminGrid">{products.filter(p=>p.active!==false).map(p=><div className="adminCard" key={p.id}><Boxes/><div><b>{p.name}</b><span>{Number(p.stock)<=5?'⚠️ Estoque baixo':'Estoque normal'}</span></div><strong>{p.stock}</strong><button onClick={()=>setEditing({...p})}>Ajustar</button></div>)}</div>}
 {tab==='customers'&&<div className="adminGrid">{customers.map(c=><div className="adminCard" key={c.id}><Users/><div><b>{c.name||'Cliente'}</b><span>{c.phone||'Sem telefone'}</span><span>Cadastrado em {new Date(c.created_at).toLocaleDateString('pt-BR')}</span></div></div>)}</div>}
 {tab==='appointments'&&<div className="adminGrid">{appointments.length?appointments.map(a=><div className="adminCard" key={a.id}><CalendarDays/><div><b>{a.service_type||'Serviço'}</b><span>{a.customer_name||'Cliente'} · {a.scheduled_at?new Date(a.scheduled_at).toLocaleString('pt-BR'):''}</span><strong>{a.status||'agendado'}</strong></div><select value={a.status||'agendado'} onChange={e=>updateAppointment(a.id,e.target.value)}>{appointmentOptions.map(s=><option key={s} value={s}>{s}</option>)}</select></div>):<p>Nenhum agendamento registrado.</p>}</div>}
 </>}{editing&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setEditing(null)}><X/></button><span className="eyebrow">CATÁLOGO</span><h2>{editing.id?'Editar produto':'Novo produto'}</h2><label>Nome<input value={editing.name||''} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><div className="two"><label>Preço<input type="number" step="0.01" value={editing.price??0} onChange={e=>setEditing({...editing,price:e.target.value})}/></label><label>Estoque<input type="number" value={editing.stock??0} onChange={e=>setEditing({...editing,stock:e.target.value})}/></label></div><label>Categoria<input value={editing.category||''} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label>Imagem<input value={editing.image_url||''} onChange={e=>setEditing({...editing,image_url:e.target.value})}/></label><label>Descrição<textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><button className="primary full" disabled={saving} onClick={saveProduct}>{saving?<Clock/>:<Save/>} {saving?'Salvando...':'Salvar produto'}</button></div></div>}</section>
}