import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,ShoppingCart,UserCircle,Menu,X,ChevronDown,Home,Tag,ShieldCheck,FileText,Phone,Plus,Trash2,Settings,Save,Truck,Heart,Stethoscope,Package}from'lucide-react';
import AdminPanel from './AdminPanel';
import'./styles.css';
import'./referenceOverrides.css';
const WA='553433341608',ADDRESS='Av. Nossa Senhora do Desterro, 1790 - Jardim Elza Amui, Uberaba - MG, 38082-350';
const DEFAULT_LOGO='/logo.svg?v=4';
const DEFAULT_BANNER={title:'Tudo para o seu pet, em um só lugar!',description:'Os melhores produtos com qualidade, preço justo e muito carinho para seu melhor amigo.',button:'VER PRODUTOS',image:'/petmaster-banner.jpg'};
const initial=[
{id:'1',name:'Ração Premium para Cães',price:89.9,cat:'Alimentação',stock:12,img:'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=700&q=80'},
{id:'2',name:'Petisco Natural',price:24.9,cat:'Alimentação',stock:25,img:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=700&q=80'},
{id:'3',name:'Cama Confort Pet',price:129.9,cat:'Casa e Conforto',stock:8,img:'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=700&q=80'},
{id:'4',name:'Shampoo Higiene & Cuidado',price:39.9,cat:'Higiene',stock:18,img:'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=700&q=80'},
{id:'5',name:'Bola Interativa para Pets',price:34.9,cat:'Brinquedos',stock:16,img:'https://images.unsplash.com/photo-1535930749574-1399327ce78f?auto=format&fit=crop&w=700&q=80'},
{id:'6',name:'Suplemento e Cuidados',price:59.9,cat:'Saúde',stock:10,img:'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=700&q=80'}];
const categories=[['Alimentação','Rações e petiscos','food'],['Acessórios','Tudo para o dia a dia','accessories'],['Higiene','Shampoo e cuidados','hygiene'],['Brinquedos','Diversão garantida','toys'],['Saúde','Medicamentos e mais','health'],['Casa e Conforto','Camas e utilidades','home']];
const categoryIcons={food:Package,accessories:Heart,hygiene:Truck,toys:Heart,health:Stethoscope,home:Home};
function Logo(){return <div className="logo"><img src={DEFAULT_LOGO} alt="PetMaster - A família do seu pet"/></div>}
function App(){
const[products,setProducts]=useState(()=>{try{return JSON.parse(localStorage.getItem('petmaster-products')||'null')||initial}catch{return initial}});
const[cart,setCart]=useState([]),[query,setQuery]=useState(''),[cat,setCat]=useState('Todos'),[admin,setAdmin]=useState(false),[editing,setEditing]=useState(null),[menu,setMenu]=useState(false),[account,setAccount]=useState(false),[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('petmaster-user')||'null')||{name:'',email:''}}catch{return{name:'',email:''}}}),[cartOpen,setCartOpen]=useState(false),[logo]=useState(DEFAULT_LOGO),[editorOpen,setEditorOpen]=useState(false),[banner,setBanner]=useState(()=>{try{return{...DEFAULT_BANNER,...JSON.parse(localStorage.getItem('petmaster-banner')||'{}')}}catch{return DEFAULT_BANNER}});
const cats=['Todos',...categories.map(c=>c[0])];
useEffect(()=>{try{localStorage.setItem('petmaster-products',JSON.stringify(products))}catch{}},[products]);
useEffect(()=>{try{localStorage.setItem('petmaster-banner',JSON.stringify(banner))}catch{}},[banner]);
const filtered=useMemo(()=>products.filter(p=>(cat==='Todos'||p.cat===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,cat,query]);
const total=cart.reduce((s,p)=>s+p.price,0);const add=p=>{if(p.stock)setCart(c=>[...c,p])};const remove=i=>setCart(c=>c.filter((_,x)=>x!==i));const scrollToProducts=()=>document.getElementById('produtos')?.scrollIntoView({behavior:'smooth'});const saveUser=()=>{localStorage.setItem('petmaster-user',JSON.stringify(user));setAccount(false)};const save=p=>{setProducts(x=>x.some(a=>a.id===p.id)?x.map(a=>a.id===p.id?p:a):[...x,p]);setEditing(null)};
function LocalProductAdmin(){return <div className="admin"><div className="adminTop"><div><span className="eyebrow">PAINEL ADMINISTRATIVO</span><h2>Produtos</h2></div><div className="adminButtons"><button className="goldBtn" onClick={()=>setEditing({id:crypto.randomUUID(),name:'Novo produto',price:0,cat:'Alimentação',stock:0,img:''})}><Plus/> Adicionar produto</button><button className="goldBtn" onClick={()=>setAdmin(false)}><X/> Fechar</button></div></div><div className="adminGrid">{products.map(p=><div className="adminCard" key={p.id}><img src={p.img||logo} alt=""/><div><b>{p.name}</b><span>{p.cat} · estoque {p.stock}</span><strong>R$ {p.price.toFixed(2).replace('.',',')}</strong></div><button onClick={()=>setEditing({...p})}>Editar</button><button className="danger" onClick={()=>setProducts(x=>x.filter(a=>a.id!==p.id))}><Trash2/></button></div>)}</div>{editing&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setEditing(null)}><X/></button><span className="eyebrow">CATÁLOGO</span><h2>{editing.name==='Novo produto'?'Novo produto':'Editar produto'}</h2><label>Nome<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><div className="two"><label>Preço<input type="number" step="0.01" value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><label>Estoque<input type="number" value={editing.stock} onChange={e=>setEditing({...editing,stock:Number(e.target.value)})}/></label></div><label>Categoria<select value={editing.cat} onChange={e=>setEditing({...editing,cat:e.target.value})}>{cats.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Foto do produto<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setEditing({...editing,img:String(r.result)});r.readAsDataURL(f)}}}/></label>{editing.img&&<img className="preview" src={editing.img} alt="Pré-visualização"/>}<button className="primary full" onClick={()=>save(editing)}><Save/> Salvar produto</button></div></div>}</div>}
function BannerEditor(){const[draft,setDraft]=useState(banner);useEffect(()=>setDraft(banner),[banner]);const saveBanner=()=>{try{localStorage.setItem('petmaster-banner',JSON.stringify(draft));setBanner(draft);setEditorOpen(false)}catch{alert('Não foi possível salvar. Tente uma imagem menor.')}};const chooseImage=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>setDraft(d=>({...d,image:String(r.result)}));r.readAsDataURL(f)};return <div className="modal" role="dialog" aria-modal="true"><div className="modalBox bannerEditor"><button type="button" className="close" aria-label="Fechar editor" onClick={()=>setEditorOpen(false)}><X/></button><span className="eyebrow">MODO EDITOR</span><h2>Editar banner</h2><p className="modalText">Altere o texto, o botão e a imagem do banner principal.</p><label>Título do banner<textarea rows="3" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Descrição<textarea rows="4" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Texto do botão<input value={draft.button} onChange={e=>setDraft({...draft,button:e.target.value})}/></label><label>Imagem do banner<input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseImage}/></label>{draft.image&&<img className="bannerPreview" src={draft.image} alt="Pré-visualização do banner"/>}<div className="editorActions"><button type="button" className="goldBtn" onClick={()=>setDraft(DEFAULT_BANNER)}>Restaurar padrão</button><button type="button" className="primary" onClick={saveBanner}><Save/> Salvar banner</button></div></div></div>}
return <>
<header><div className="topbar"><Logo/><div className="search"><input placeholder="Buscar produtos..." value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={scrollToProducts} aria-label="Buscar"><Search/></button></div><button className="account" onClick={()=>setAccount(true)}><UserCircle/><span><b>Minha conta</b><small>{user.name||'Entrar / Cadastrar'}</small></span></button><button className="cartButton" onClick={()=>setCartOpen(true)}><ShoppingCart/><span>Meu carrinho</span><em>{cart.length}</em></button><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div><div className="navline"><button className="allCategories" onClick={()=>setMenu(!menu)}><Menu/> TODAS CATEGORIAS <ChevronDown/></button><nav className={menu?'open':''}><a className="active" href="#inicio"><Home/> Início</a><a href="#produtos"><Package/> Produtos</a><a href="#promocoes"><Tag/> Promoções</a><a href="#marcas"><ShieldCheck/> Marcas</a><a href="#blog"><FileText/> Blog</a><a href="#contato"><Phone/> Contato</a></nav></div></header>
{admin?<AdminPanel onClose={()=>setAdmin(false)}/>:<main id="inicio">
<section className="heroBanner"><button type="button" className="heroEditorButton" onClick={()=>setEditorOpen(true)}><Settings/> Editar banner</button><div className="heroCopy"><h1>{banner.title}</h1><p>{banner.description}</p><button className="heroButton" onClick={scrollToProducts}>{banner.button}</button></div><div className="heroPets" style={banner.image?{backgroundImage:`url(${banner.image})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}>{!banner.image&&<><div className="sun"></div><div className="dog" aria-label="Cachorro"></div><div className="cat" aria-label="Gato"></div></>}</div></section>
<section className="categoryGrid">{categories.map(([name,desc,key])=>{const I=categoryIcons[key];return <button className="categoryCard" key={name} onClick={()=>{setCat(name);scrollToProducts()}}><div className={'categoryIcon '+key}><I/></div><b>{name}</b><span>{desc}</span></button>})}</section>
<section id="produtos" className="section products"><div className="sectionHead"><div><span className="eyebrow">LOJA PETMASTER</span><h2>Escolhas para quem você ama.</h2></div><div className="filters">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><div className="productGrid">{filtered.map(p=><article className="product" key={p.id}><div className="productImg"><img src={p.img||logo} alt={p.name}/><button onClick={()=>add(p)} disabled={!p.stock}><Plus/></button></div><span>{p.cat}</span><h3>{p.name}</h3><strong>R$ {p.price.toFixed(2).replace('.',',')}</strong><small>{p.stock>0?'Em estoque':'Indisponível'}</small></article>)}</div></section>
<section id="promocoes" className="featureStrip"><div><span className="eyebrow">PETMASTER</span><h2>Qualidade, cuidado e praticidade.</h2><p>Encontre tudo o que seu pet precisa e fale diretamente com nossa equipe.</p></div><a className="goldBtn" href={`https://wa.me/${WA}?text=Olá%20PetMaster!%20Quero%20conhecer%20as%20promoções.`}>Ver promoções <Phone/></a></section>
<section id="marcas" className="infoSection"><span className="eyebrow">CUIDADO COMPLETO</span><h2>Produtos escolhidos para o bem-estar do seu pet.</h2><p>Alimentação, acessórios, higiene, brinquedos, saúde e conforto em um só lugar.</p></section>
<section id="blog" className="infoSection compact"><span className="eyebrow">BLOG PETMASTER</span><h2>Dicas para cuidar melhor do seu melhor amigo.</h2><p>Conteúdos e orientações para uma rotina mais saudável e feliz.</p></section>
<section id="contato" className="contact"><div><span className="eyebrow">VENHA NOS VISITAR</span><h2>PetMaster. A família do seu pet.</h2><p>{ADDRESS}</p><a className="goldBtn" href={`https://wa.me/${WA}?text=Olá%20PetMaster!`}>Falar no WhatsApp <Phone/></a></div><div className="contactInfo"><b><Phone/> (34) 3334-1608</b><span>Segunda a sábado · 08:00 às 20:00</span><span>Domingo · 08:00 às 13:00</span></div></section></main>}
<footer><Logo/><span>© {new Date().getFullYear()} PetMaster. Todos os direitos reservados.</span><button type="button" onClick={()=>setEditorOpen(true)}><Settings/> Editar banner</button><button type="button" onClick={()=>setAdmin(true)}><Settings/> Administração</button></footer>
{!admin&&!editorOpen&&<button type="button" className="editorFloating" onClick={()=>setEditorOpen(true)}><Settings/> Editar banner</button>}
{editorOpen&&<BannerEditor/>}
{account&&<div className="modal"><div className="modalBox accountBox"><button className="close" onClick={()=>setAccount(false)}><X/></button><span className="eyebrow">MINHA CONTA</span><h2>Seus dados</h2><p className="modalText">Salve seus dados para agilizar seu atendimento.</p><label>Nome<input value={user.name} placeholder="Seu nome" onChange={e=>setUser({...user,name:e.target.value})}/></label><label>E-mail<input value={user.email} placeholder="seu@email.com" onChange={e=>setUser({...user,email:e.target.value})}/></label><button className="primary full" onClick={saveUser}>Salvar dados</button></div></div>}
{cartOpen&&<div className="modal"><div className="cartBox"><button className="close" onClick={()=>setCartOpen(false)}><X/></button><span className="eyebrow">MEU CARRINHO</span><h2>Seu pedido</h2>{cart.length?<>{cart.map((p,i)=><div className="cartItem" key={i}><img src={p.img||logo} alt=""/><div><b>{p.name}</b><span>R$ {p.price.toFixed(2).replace('.',',')}</span></div><button onClick={()=>remove(i)}><Trash2/></button></div>)}<div className="cartTotal"><span>Total</span><b>R$ {total.toFixed(2).replace('.',',')}</b></div>{total>=399&&<p className="free">Você ganhou frete grátis.</p>}<a className="primary full" href={`https://wa.me/${WA}?text=${encodeURIComponent('Olá PetMaster! Quero fazer um pedido no valor de R$ '+total.toFixed(2))}`}>Finalizar pelo WhatsApp <Phone/></a></>:<p>Seu carrinho está vazio.</p>}</div></div>}
</>}
createRoot(document.getElementById('root')).render(<App/>);
