import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,ShoppingCart,UserCircle,Menu,X,ChevronDown,Home,Tag,ShieldCheck,FileText,Phone,Plus,Trash2,Settings,Save,Truck,Heart,Stethoscope,Package,MousePointer2,ImagePlus,Edit3,Eye,EyeOff}from'lucide-react';
import'./styles.css';
import'./referenceOverrides.css';
const WA='553433341608',ADDRESS='Av. Nossa Senhora do Desterro, 1790 - Jardim Elza Amui, Uberaba - MG, 38082-350';
const DEFAULT_LOGO='/logo.svg?v=4';
const initial=[
{id:'1',name:'Ração Premium para Cães',price:89.9,cat:'Alimentação',stock:12,img:'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=700&q=80'},
{id:'2',name:'Petisco Natural',price:24.9,cat:'Alimentação',stock:25,img:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=700&q=80'},
{id:'3',name:'Cama Confort Pet',price:129.9,cat:'Casa e Conforto',stock:8,img:'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=700&q=80'},
{id:'4',name:'Shampoo Higiene & Cuidado',price:39.9,cat:'Higiene',stock:18,img:'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=700&q=80'},
{id:'5',name:'Bola Interativa para Pets',price:34.9,cat:'Brinquedos',stock:16,img:'https://images.unsplash.com/photo-1535930749574-1399327ce78f?auto=format&fit=crop&w=700&q=80'},
{id:'6',name:'Suplemento e Cuidados',price:59.9,cat:'Saúde',stock:10,img:'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=700&q=80'}];
const categories=[['Alimentação','Rações e petiscos','food'],['Acessórios','Tudo para o dia a dia','accessories'],['Higiene','Shampoo e cuidados','hygiene'],['Brinquedos','Diversão garantida','toys'],['Saúde','Medicamentos e mais','health'],['Casa e Conforto','Camas e utilidades','home']];
const categoryIcons={food:Package,accessories:Heart,hygiene:Truck,toys:Heart,health:Stethoscope,home:Home};
function Logo({onClick}){const src=(()=>{try{return localStorage.getItem('petmaster-logo')||DEFAULT_LOGO}catch{return DEFAULT_LOGO}})();return <div className="logo" onClick={onClick} data-site-edit="logo"><img src={src} alt="PetMaster - A família do seu pet"/></div>}
function SiteEditor({onClose,onLogoChange}){const fileRef=useRef(null);const[logo,setLogo]=useState(()=>{try{return localStorage.getItem('petmaster-logo')||DEFAULT_LOGO}catch{return DEFAULT_LOGO}});const upload=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const value=String(r.result);setLogo(value);try{localStorage.setItem('petmaster-logo',value)}catch{}onLogoChange(value)};r.readAsDataURL(f)};return <div className="editorBar"><div><b>Modo de edição</b><span>Clique com o botão esquerdo em textos, botões, imagens ou na logo para editar.</span></div><div className="editorActions"><button onClick={()=>fileRef.current?.click()}><ImagePlus/> Alterar logo</button><button onClick={()=>{try{localStorage.removeItem('petmaster-logo')}catch{}setLogo(DEFAULT_LOGO);onLogoChange(DEFAULT_LOGO)}}>Restaurar logo</button><button className="editorClose" onClick={onClose}><EyeOff/> Sair da edição</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={upload}/></div></div>}
function App(){
const[products,setProducts]=useState(()=>{try{return JSON.parse(localStorage.getItem('petmaster-products')||'null')||initial}catch{return initial}});
const[cart,setCart]=useState([]),[query,setQuery]=useState(''),[cat,setCat]=useState('Todos'),[admin,setAdmin]=useState(false),[editing,setEditing]=useState(null),[menu,setMenu]=useState(false),[account,setAccount]=useState(false),[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('petmaster-user')||'null')||{name:'',email:''}}catch{return{name:'',email:''}}}),[cartOpen,setCartOpen]=useState(false),[editMode,setEditMode]=useState(false),[logo,setLogo]=useState(()=>{try{return localStorage.getItem('petmaster-logo')||DEFAULT_LOGO}catch{return DEFAULT_LOGO}});
const cats=['Todos',...categories.map(c=>c[0])];
useEffect(()=>{try{localStorage.setItem('petmaster-products',JSON.stringify(products))}catch{}},[products]);
useEffect(()=>{if(!editMode)return;const handler=e=>{if(e.target.closest('.editorBar,.admin,.modal,footer button,.search input,.cartButton,.account,.mobileMenu'))return;const el=e.target.closest('[data-site-edit]');if(!el)return;e.preventDefault();e.stopPropagation();const type=el.dataset.siteEdit;const current=(el.innerText||'').trim();if(type==='logo'){document.getElementById('logo-upload-input')?.click();return}if(type==='image'){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=ev=>{const f=ev.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{el.dataset.editedImage=String(r.result);el.style.backgroundImage=`url("${String(r.result)}")`;const img=el.querySelector('img');if(img)img.src=String(r.result);};r.readAsDataURL(f)};input.click();return}const next=window.prompt('Digite o novo texto:',current);if(next!==null&&next.trim()!=='' ){el.innerText=next;el.dataset.editedText=next;try{const key=el.dataset.siteEditKey;if(key)localStorage.setItem('petmaster-text-'+key,next)}catch{}}};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[editMode]);
const filtered=useMemo(()=>products.filter(p=>(cat==='Todos'||p.cat===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[products,cat,query]);
const total=cart.reduce((s,p)=>s+p.price,0);const add=p=>{if(p.stock)setCart(c=>[...c,p])};const remove=i=>setCart(c=>c.filter((_,x)=>x!==i));const scrollToProducts=()=>document.getElementById('produtos')?.scrollIntoView({behavior:'smooth'});const saveUser=()=>{localStorage.setItem('petmaster-user',JSON.stringify(user));setAccount(false)};const save=p=>{setProducts(x=>x.some(a=>a.id===p.id)?x.map(a=>a.id===p.id?p:a):[...x,p]);setEditing(null)};
const EditText=({id,children,className='',...props})=>{let value=children;try{value=localStorage.getItem('petmaster-text-'+id)||children}catch{}return <span className={className} data-site-edit="text" data-site-edit-key={id} {...props}>{value}</span>};
function Admin(){return <div className="admin"><div className="adminTop"><div><span className="eyebrow">PAINEL ADMINISTRATIVO</span><h2>Produtos</h2></div><div className="adminButtons"><button className="goldBtn" onClick={()=>setEditing({id:crypto.randomUUID(),name:'Novo produto',price:0,cat:'Alimentação',stock:0,img:''})}><Plus/> Adicionar produto</button><button className="primary" onClick={()=>setEditMode(true)}><MousePointer2/> Editar site visualmente</button></div></div><div className="adminGrid">{products.map(p=><div className="adminCard" key={p.id}><img src={p.img||logo} alt=""/><div><b>{p.name}</b><span>{p.cat} · estoque {p.stock}</span><strong>R$ {p.price.toFixed(2).replace('.',',')}</strong></div><button onClick={()=>setEditing({...p})}>Editar</button><button className="danger" onClick={()=>setProducts(x=>x.filter(a=>a.id!==p.id))}><Trash2/></button></div>)}</div>{editing&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setEditing(null)}><X/></button><span className="eyebrow">CATÁLOGO</span><h2>{editing.name==='Novo produto'?'Novo produto':'Editar produto'}</h2><label>Nome<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><div className="two"><label>Preço<input type="number" step="0.01" value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><label>Estoque<input type="number" value={editing.stock} onChange={e=>setEditing({...editing,stock:Number(e.target.value)})}/></label></div><label>Categoria<select value={editing.cat} onChange={e=>setEditing({...editing,cat:e.target.value})}>{cats.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Foto do produto<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setEditing({...editing,img:String(r.result)});r.readAsDataURL(f)}}}/></label>{editing.img&&<img className="preview" src={editing.img} alt="Pré-visualização"/>}<button className="primary full" onClick={()=>save(editing)}><Save/> Salvar produto</button></div></div>}</div>}
return <>{editMode&&<><SiteEditor onClose={()=>setEditMode(false)} onLogoChange={setLogo}/><input id="logo-upload-input" hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const v=String(r.result);setLogo(v);try{localStorage.setItem('petmaster-logo',v)}catch{}};r.readAsDataURL(f)}}/></>}
<header><div className="topbar"><Logo onClick={editMode?()=>document.getElementById('logo-upload-input')?.click():undefined}/><div className="search"><input placeholder="Buscar produtos..." value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={scrollToProducts} aria-label="Buscar"><Search/></button></div><button className="account" onClick={()=>setAccount(true)}><UserCircle/><span><b>Minha conta</b><small>{user.name||'Entrar / Cadastrar'}</small></span></button><button className="cartButton" onClick={()=>setCartOpen(true)}><ShoppingCart/><span>Meu carrinho</span><em>{cart.length}</em></button><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div><div className="navline"><button className="allCategories" onClick={()=>setMenu(!menu)}><Menu/> TODAS CATEGORIAS <ChevronDown/></button><nav className={menu?'open':''}><a className="active" href="#inicio"><Home/> Início</a><a href="#produtos"><Package/> Produtos</a><a href="#promocoes"><Tag/> Promoções</a><a href="#marcas"><ShieldCheck/> Marcas</a><a href="#blog"><FileText/> Blog</a><a href="#contato"><Phone/> Contato</a></nav></div></header>
{admin?<Admin/>:<main id="inicio">
<section className="heroBanner"><div className="heroCopy"><h1 data-site-edit="text" data-site-edit-key="hero-title"><EditText id="hero-title">Tudo para o seu pet, em um só lugar!</EditText></h1><p data-site-edit="text" data-site-edit-key="hero-description"><EditText id="hero-description">Os melhores produtos com qualidade, preço justo e muito carinho para seu melhor amigo.</EditText></p><button className="heroButton" data-site-edit="text" data-site-edit-key="hero-button" onClick={scrollToProducts}><EditText id="hero-button">VER PRODUTOS</EditText></button></div><div className="heroPets"><div className="sun"></div><div className="dog" aria-label="Cachorro" data-site-edit="image"></div><div className="cat" aria-label="Gato" data-site-edit="image"></div></div></section>
<section className="categoryGrid">{categories.map(([name,desc,key],i)=>{const I=categoryIcons[key];return <button className="categoryCard" key={name} onClick={()=>{setCat(name);scrollToProducts()}}><div className={'categoryIcon '+key}><I/></div><b data-site-edit="text" data-site-edit-key={'cat-name-'+i}>{name}</b><span data-site-edit="text" data-site-edit-key={'cat-desc-'+i}>{desc}</span></button>})}</section>
<section id="produtos" className="section products"><div className="sectionHead"><div><span className="eyebrow" data-site-edit="text" data-site-edit-key="products-eyebrow">LOJA PETMASTER</span><h2 data-site-edit="text" data-site-edit-key="products-title">Escolhas para quem você ama.</h2></div><div className="filters">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><div className="productGrid">{filtered.map(p=><article className="product" key={p.id}><div className="productImg"><img src={p.img||logo} alt={p.name}/><button onClick={()=>add(p)} disabled={!p.stock}><Plus/></button></div><span>{p.cat}</span><h3>{p.name}</h3><strong>R$ {p.price.toFixed(2).replace('.',',')}</strong><small>{p.stock>0?'Em estoque':'Indisponível'}</small></article>)}</div></section>
<section id="promocoes" className="featureStrip"><div><span className="eyebrow" data-site-edit="text" data-site-edit-key="feature-eyebrow">PETMASTER</span><h2 data-site-edit="text" data-site-edit-key="feature-title">Qualidade, cuidado e praticidade.</h2><p data-site-edit="text" data-site-edit-key="feature-description">Encontre tudo o que seu pet precisa e fale diretamente com nossa equipe.</p></div><a className="goldBtn" href={`https://wa.me/${WA}?text=Olá%20PetMaster!%20Quero%20conhecer%20as%20promoções.`}><span data-site-edit="text" data-site-edit-key="feature-button">Ver promoções</span> <Phone/></a></section>
<section id="marcas" className="infoSection"><span className="eyebrow">CUIDADO COMPLETO</span><h2 data-site-edit="text" data-site-edit-key="brands-title">Produtos escolhidos para o bem-estar do seu pet.</h2><p data-site-edit="text" data-site-edit-key="brands-description">Alimentação, acessórios, higiene, brinquedos, saúde e conforto em um só lugar.</p></section>
<section id="blog" className="infoSection compact"><span className="eyebrow">BLOG PETMASTER</span><h2 data-site-edit="text" data-site-edit-key="blog-title">Dicas para cuidar melhor do seu melhor amigo.</h2><p data-site-edit="text" data-site-edit-key="blog-description">Conteúdos e orientações para uma rotina mais saudável e feliz.</p></section>
<section id="contato" className="contact"><div><span className="eyebrow">VENHA NOS VISITAR</span><h2 data-site-edit="text" data-site-edit-key="contact-title">PetMaster. A família do seu pet.</h2><p data-site-edit="text" data-site-edit-key="contact-address">{ADDRESS}</p><a className="goldBtn" href={`https://wa.me/${WA}?text=Olá%20PetMaster!`}>Falar no WhatsApp <Phone/></a></div><div className="contactInfo"><b><Phone/> (34) 3334-1608</b><span>Segunda a sábado · 08:00 às 20:00</span><span>Domingo · 08:00 às 13:00</span></div></section></main>}
<footer><Logo onClick={editMode?()=>document.getElementById('logo-upload-input')?.click():undefined}/><span data-site-edit="text" data-site-edit-key="footer">© {new Date().getFullYear()} PetMaster. Todos os direitos reservados.</span><button onClick={()=>setAdmin(true)}><Settings/> Administração</button></footer>
{account&&<div className="modal"><div className="modalBox accountBox"><button className="close" onClick={()=>setAccount(false)}><X/></button><span className="eyebrow">MINHA CONTA</span><h2>Seus dados</h2><p className="modalText">Salve seus dados para agilizar seu atendimento.</p><label>Nome<input value={user.name} placeholder="Seu nome" onChange={e=>setUser({...user,name:e.target.value})}/></label><label>E-mail<input value={user.email} placeholder="seu@email.com" onChange={e=>setUser({...user,email:e.target.value})}/></label><button className="primary full" onClick={saveUser}>Salvar dados</button></div></div>}
{cartOpen&&<div className="modal"><div className="cartBox"><button className="close" onClick={()=>setCartOpen(false)}><X/></button><span className="eyebrow">MEU CARRINHO</span><h2>Seu pedido</h2>{cart.length?<>{cart.map((p,i)=><div className="cartItem" key={i}><img src={p.img||logo} alt=""/><div><b>{p.name}</b><span>R$ {p.price.toFixed(2).replace('.',',')}</span></div><button onClick={()=>remove(i)}><Trash2/></button></div>)}<div className="cartTotal"><span>Total</span><b>R$ {total.toFixed(2).replace('.',',')}</b></div>{total>=399&&<p className="free">Você ganhou frete grátis.</p>}<a className="primary full" href={`https://wa.me/${WA}?text=${encodeURIComponent('Olá PetMaster! Quero fazer um pedido no valor de R$ '+total.toFixed(2))}`}>Finalizar pelo WhatsApp <Phone/></a></>:<p>Seu carrinho está vazio.</p>}</div></div>}
{!editMode&&!admin&&<button className="floatingEditor" onClick={()=>setEditMode(true)} title="Ativar modo de edição"><Edit3/> Editar site</button>}
</>}
createRoot(document.getElementById('root')).render(<App/>);
