import React,{useEffect,useRef,useState}from'react';
import{ImagePlus,Save,Trash2,RotateCcw,X,Move,Type,Image as ImageIcon,Undo2,EyeDropper,Palette}from'lucide-react';
import'./siteVisualEditor.css';
const STORAGE='petmaster-visual-edits';
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return{}}};
const write=v=>{try{localStorage.setItem(STORAGE,JSON.stringify(v));return true}catch{return false}};
function transparentInfo(file,cb){const r=new FileReader();r.onload=()=>{const src=String(r.result);const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d');x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let transparent=false;for(let i=3;i<d.length;i+=4){if(d[i]<250){transparent=true;break}}cb(src,transparent)}catch{cb(src,false)}};img.src=src};r.readAsDataURL(file)}
const apply=(el,v)=>{if(!el)return;el.style.transform=`translate(${v.x||0}px,${v.y||0}px) rotate(${v.rotate||0}deg) scale(${v.scale||1})`;if(v.width)el.style.width=`${v.width}px`;if(v.height)el.style.height=`${v.height}px`;el.style.visibility=v.hidden?'hidden':'';if(v.text!==undefined)el.textContent=v.text;if(v.color)el.style.color=v.color;if(v.src&&el.tagName==='IMG')el.src=v.src};
export default function SiteVisualEditor({active,onExit}){const[selected,setSelected]=useState(null);const[edits,setEdits]=useState(read);const[drag,setDrag]=useState(null);const[fileRef]=[useRef(null)];const colorRef=useRef(null);const[status,setStatus]=useState('');
useEffect(()=>{if(!active)return;const els=[...document.querySelectorAll('[data-site-edit],img,button,a,h1,h2,h3,h4,h5,p,span,small,strong,label,section,article,header,footer')];const saved=read();els.forEach((el,i)=>{if(el.closest('.visual-editor'))return;if(!el.dataset.editorId)el.dataset.editorId='editor-'+i;el.classList.add('editor-target');apply(el,saved[el.dataset.editorId]||{})});const down=e=>{if(e.target.closest('.visual-editor'))return;const el=e.target.closest('[data-site-edit],img,button,a,h1,h2,h3,h4,h5,p,span,small,strong,label,section,article,header,footer');if(!el||el.closest('.visual-editor'))return;e.preventDefault();e.stopPropagation();const id=el.dataset.editorId||'editor-'+Math.random().toString(36).slice(2);el.dataset.editorId=id;const base=read()[id]||{};setSelected({id,el});setDrag({id,el,sx:e.clientX,sy:e.clientY,baseX:base.x||0,baseY:base.y||0})};const move=e=>{if(!drag)return;const n={...read(),[drag.id]:{...(read()[drag.id]||{}),x:drag.baseX+(e.clientX-drag.sx),y:drag.baseY+(e.clientY-drag.sy)}};setEdits(n);apply(drag.el,n[drag.id]);write(n)};const up=()=>setDrag(null);document.addEventListener('mousedown',down,true);document.addEventListener('mousemove',move,true);document.addEventListener('mouseup',up,true);return()=>{document.removeEventListener('mousedown',down,true);document.removeEventListener('mousemove',move,true);document.removeEventListener('mouseup',up,true);els.forEach(el=>el.classList.remove('editor-target'))}},[active,drag]);
useEffect(()=>{Object.entries(edits).forEach(([id,v])=>apply(document.querySelector(`[data-editor-id="${id}"]`),v))},[edits]);
const update=v=>{if(!selected)return;const current=read();const n={...current,[selected.id]:{...(current[selected.id]||{}),...v}};setEdits(n);apply(selected.el,n[selected.id]);write(n)};
const save=()=>{write(edits);setStatus('✓ Edição salva com sucesso');setTimeout(()=>setStatus(''),2200)};
const editText=()=>{if(!selected)return;const value=window.prompt('Digite o novo texto:',selected.el.innerText||selected.el.textContent||'');if(value!==null)update({text:value})};
const upload=()=>fileRef.current?.click();const onFile=e=>{const f=e.target.files?.[0];if(!f||!selected)return;transparentInfo(f,(src,transparent)=>{update({src,transparent,hidden:false});if(selected.el.tagName==='IMG')selected.el.src=src;else{selected.el.style.backgroundImage=`url(${src})`;selected.el.style.backgroundSize='cover'}});e.target.value=''};
const removePhoto=()=>{if(!selected)return;const isImage=selected.el.tagName==='IMG'||selected.el.dataset.siteEdit==='image'||getComputedStyle(selected.el).backgroundImage!=='none';if(!isImage){window.alert('Selecione uma imagem para remover.');return}update({hidden:true})};const restore=()=>{if(selected)update({hidden:false})};
const chooseColor=()=>colorRef.current?.click();const onColor=e=>update({color:e.target.value});const pickFromSite=()=>{if('EyeDropper'in window){new window.EyeDropper().open().then(r=>update({color:r.sRGBHex})).catch(()=>{})}else window.alert('O conta-gotas não está disponível neste navegador. Use o botão Cor.')};
if(!active)return null;const s=selected&&edits[selected.id]||read()[selected?.id]||{};const rect=selected?.el?.getBoundingClientRect();const naturalW=rect?.width||0,naturalH=rect?.height||0;
return <div className="visual-editor"><div className="ve-toolbar"><b>EDITOR VISUAL</b><span>{drag?'Solte para posicionar':'Clique, arraste e edite qualquer elemento'}</span><button onClick={editText}><Type/> Texto</button><button onClick={upload}><ImagePlus/> Trocar imagem</button><button onClick={removePhoto}><Trash2/> Remover foto</button><button onClick={restore}><Undo2/> Mostrar</button><button onClick={chooseColor}><Palette/> Cor</button><button onClick={pickFromSite}><EyeDropper/> Conta-gotas</button><input ref={colorRef} hidden type="color" value={s.color||'#111827'} onChange={onColor}/><button onClick={()=>update({rotate:(s.rotate||0)-15})}><RotateCcw/></button><button onClick={()=>update({rotate:(s.rotate||0)+15})}>↻</button><button className="ve-save" onClick={save}><Save/> SALVAR EDIÇÃO</button><button className="ve-exit" onClick={onExit}><X/> Sair</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={onFile}/></div>{selected&&<div className="ve-panel"><b>Elemento selecionado</b><div className="ve-grid"><label>X<input type="number" value={Math.round(s.x||0)} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Y<input type="number" value={Math.round(s.y||0)} onChange={e=>update({y:Number(e.target.value)})}/></label><label>Largura<input type="number" min="1" value={Math.round(s.width||naturalW)} onChange={e=>update({width:Number(e.target.value)})}/></label><label>Altura<input type="number" min="1" value={Math.round(s.height||naturalH)} onChange={e=>update({height:Number(e.target.value)})}/></label></div><label>Escala<input type="number" min="0.1" step="0.1" value={s.scale||1} onChange={e=>update({scale:Number(e.target.value)})}/></label><label>Rotação<input type="number" value={s.rotate||0} onChange={e=>update({rotate:Number(e.target.value)})}/></label><div className="ve-color"><span>Cor do texto</span><button aria-label="Escolher cor" style={{background:s.color||'#111827'}} onClick={chooseColor}/></div>{s.transparent!==undefined&&<small>{s.transparent?'🟢 Fundo transparente detectado':'🟡 Não foi detectada transparência no arquivo'}</small>}</div>}{status&&<div className="ve-status">{status}</div>}<div className="ve-hint"><Move/> Arraste · <Type/> Texto · <ImageIcon/> Imagem · <EyeDropper/> Cor · 💾 Salvar</div></div>}
