import React,{useEffect,useRef,useState}from'react';
import{ImagePlus,Save,Trash2,Copy,BringToFront,SendToBack,RotateCcw,X,Move,Type,Image as ImageIcon}from'lucide-react';
import'./siteVisualEditor.css';

const STORAGE='petmaster-visual-edits';
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return{}}};
const write=v=>{try{localStorage.setItem(STORAGE,JSON.stringify(v))}catch{}};

function transparentInfo(file,cb){
 const r=new FileReader();r.onload=()=>{const src=String(r.result);const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d');x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let transparent=false;for(let i=3;i<d.length;i+=4){if(d[i]<250){transparent=true;break}}cb(src,transparent)}catch{cb(src,false)}};img.src=src};r.readAsDataURL(file)}

export default function SiteVisualEditor({active,onExit}){
 const[selected,setSelected]=useState(null);const[edits,setEdits]=useState(read);const[drag,setDrag]=useState(null);const fileRef=useRef(null);
 useEffect(()=>{if(!active)return;const els=[...document.querySelectorAll('[data-site-edit],img,button,a,h1,h2,h3,h4,p,span,section,article,header,footer')];els.forEach((el,i)=>{if(el.closest('.visual-editor'))return;if(!el.dataset.editorId)el.dataset.editorId='editor-'+i;el.classList.add('editor-target')});const down=e=>{if(e.target.closest('.visual-editor'))return;const el=e.target.closest('[data-site-edit],img,button,a,h1,h2,h3,h4,p,span,section,article,header,footer');if(!el||el.closest('.visual-editor'))return;e.preventDefault();e.stopPropagation();const id=el.dataset.editorId||'editor-'+Math.random().toString(36).slice(2);el.dataset.editorId=id;setSelected({id,el});const r=el.getBoundingClientRect();setDrag({id,el,sx:e.clientX,sy:e.clientY,ox:r.left,oy:r.top})};const move=e=>{if(!drag)return;const dx=e.clientX-drag.sx,dy=e.clientY-drag.sy;const existing=edits[drag.id]||{};const next={...edits,[drag.id]:{...existing,x:(existing.x||0)+dx,y:(existing.y||0)+dy}};setEdits(next);drag.el.style.transform=`translate(${next[drag.id].x}px,${next[drag.id].y}px)${next[drag.id].rotate?` rotate(${next[drag.id].rotate}deg)`:''}`};const up=()=>{if(drag){write(edits);setDrag(null)}};document.addEventListener('mousedown',down,true);document.addEventListener('mousemove',move,true);document.addEventListener('mouseup',up,true);return()=>{document.removeEventListener('mousedown',down,true);document.removeEventListener('mousemove',move,true);document.removeEventListener('mouseup',up,true);els.forEach(el=>el.classList.remove('editor-target'))}},[active,drag,edits]);
 useEffect(()=>{Object.entries(edits).forEach(([id,v])=>{const el=document.querySelector(`[data-editor-id="${id}"]`);if(!el)return;el.style.transform=`translate(${v.x||0}px,${v.y||0}px) rotate(${v.rotate||0}deg) scale(${v.scale||1})`;if(v.text!==undefined)el.textContent=v.text;if(v.src&&el.tagName==='IMG')el.src=v.src})},[edits]);
 const update=v=>{if(!selected)return;const n={...edits,[selected.id]:{...(edits[selected.id]||{}),...v}};setEdits(n);write(n);setTimeout(()=>{const el=document.querySelector(`[data-editor-id="${selected.id}"]`);if(el){if(v.text!==undefined)el.textContent=v.text;if(v.src&&el.tagName==='IMG')el.src=v.src;el.style.transform=`translate(${n[selected.id].x||0}px,${n[selected.id].y||0}px) rotate(${n[selected.id].rotate||0}deg) scale(${n[selected.id].scale||1})`}},0)};
 const editText=()=>{if(!selected)return;const el=selected.el;const value=window.prompt('Novo texto:',el.innerText||el.textContent||'');if(value!==null)update({text:value})};
 const upload=()=>fileRef.current?.click();
 const onFile=e=>{const f=e.target.files?.[0];if(!f||!selected)return;transparentInfo(f,(src,transparent)=>{update({src,transparent});const el=selected.el;if(el.tagName==='IMG')el.src=src;else{el.style.backgroundImage=`url(${src})`;el.style.backgroundSize='cover'}});e.target.value=''};
 const del=()=>{if(!selected)return;update({hidden:true});selected.el.style.visibility='hidden';setSelected(null)};
 if(!active)return null;const s=selected&&edits[selected.id]||{};
 return <div className="visual-editor"><div className="ve-toolbar"><b>EDITOR VISUAL</b><span>Arraste qualquer elemento. Clique para selecionar.</span><button onClick={editText}><Type/> Texto</button><button onClick={upload}><ImagePlus/> Imagem</button><button onClick={()=>update({rotate:(s.rotate||0)-15})}><RotateCcw/></button><button onClick={()=>update({rotate:(s.rotate||0)+15})}>↻</button><button onClick={()=>update({scale:Math.max(.2,(s.scale||1)-.1)})}>−</button><button onClick={()=>update({scale:(s.scale||1)+.1})}>+</button><button onClick={del}><Trash2/></button><button onClick={()=>write(edits)}><Save/> Salvar</button><button className="ve-exit" onClick={onExit}><X/> Sair</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={onFile}/></div>{selected&&<div className="ve-panel"><b>Elemento selecionado</b><label>X<input type="number" value={Math.round(s.x||0)} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Y<input type="number" value={Math.round(s.y||0)} onChange={e=>update({y:Number(e.target.value)})}/></label><label>Escala<input type="number" step=".1" value={s.scale||1} onChange={e=>update({scale:Number(e.target.value)})}/></label><label>Rotação<input type="number" value={s.rotate||0} onChange={e=>update({rotate:Number(e.target.value)})}/></label>{s.transparent!==undefined&&<small>{s.transparent?'🟢 Fundo transparente detectado':'🟡 Não foi detectada transparência no arquivo'}</small>}</div>}<div className="ve-hint"><Move/> Mover · <Type/> editar texto · <ImageIcon/> trocar imagem</div></div>
}
